CONFIG_ZMK_SPLIT=n
CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_IIDX_HID=y

CONFIG_USB_HID_DEVICE_COUNT=2
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_SN=""
CONFIG_USB_SELF_POWERED=n
CONFIG_USB_MAX_POWER=50
CONFIG_USB_HID_POLL_INTERVAL_MS=4
CONFIG_ZMK_USB_LOGGING=n

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_SETTINGS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
